version: '3'
services:
  servicea:
    build:
      context: ./serviceA
    ports:
      - "8080:8080"
  serviceb:
    build:
      context: ./serviceB
    ports:
      - "8081:8081"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
